name: Tag & Make Release PR

on:
  pull_request:
    types:
      - "closed"
    branches:
      - "main"

jobs:
  build_and_release:
    if: github.event.pull_request.merged == true && !startsWith(github.head_ref, 'release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: extractions/setup-just@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: |
          uv sync --frozen

      - name: Config Git
        run: |
          git config user.name "Release Bot"
          git config user.email "dev@beauhurst.com"

      - name: Create Release
        id: version
        run: |
          just release
          echo "VERSION=$(just --evaluate current_version)" >>$GITHUB_OUTPUT

      - name: Create release branch, push branch, tag and create PR
        env:
          TAG_NAME: "v${{ steps.version.outputs.VERSION }}"
          BRANCH_NAME: "release-v${{ steps.version.outputs.VERSION }}"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"
          git push origin tag "$TAG_NAME"

          # create release PR
          gh pr create \
            --title "Release $TAG_NAME" \
            --head "$(git branch --show-current)" \
            --fill \
            --base main
